### ISSUE TITLE
Add Image view from gist

### ISSUE THREAD

**Issue by RandomFractals** [vsls-contrib/gistpad#91]
related: image view is broken.

should this displaly an image?

![gistpad-image-preview](https://user-images.githubusercontent.com/656833/71767365-2ca0ce00-2ed1-11ea-9c7f-0f4c82084adf.png)

_Originally posted by @RandomFractals in https://github.com/vsls-contrib/gistpad/issues/89#issuecomment-570792346_

**Comment by RandomFractals** [comment]
expected: .png and .svg from gists to work

not sure what that entails on your end, but those are very common image files used and shared in gists by devs.

**Comment by lostintangent** [comment]
Yeah this did work, but it may have regressed at some point. I’ll take a look today.

**Comment by lostintangent** [comment]
This should now be fixed!

**Comment by RandomFractals** [comment]
I still get an error for that thumbnail.png:

https://gist.githubusercontent.com/domoritz/455e1c7872c4b38a58b90df0c3d7b1b9/raw/01f0fe739291d0aabf4c2e10651ff0b6652f4c38/thumbnail.png
